version: '3.1'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "9000:4000"
    volumes:
      - .:/sdcapi
    environment:
      DB_HOST: "172.31.12.19"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "mypassword"
      DB_NAME: "sdcquestionsandanswers"

  nginx:
    image: nginx:1.21.0-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./public:/var/www/public"