# docker-compose.yml
version: '3.1'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "9000:4000"
    volumes:
      - .:/sdcapi
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASS: "mypassword"
      DB_NAME: "sdcquestionsandanswers"
  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: sdcquestionsandanswers
    ports:
      - "3005:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata: