version: '3.1'
services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: sdcquestionsandanswers
    ports:
      - "5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
